kafka:
  topic:
    hub: telemetry.hubs.v1
    sensor: telemetry.sensors.v1
    snapshot: telemetry.snapshots.v1
  group:
    id: telemetry.aggregator
  bootstrap:
    server: localhost:9092
  consumer:
    snapshot:
      group:
        id: snapshot-group
    hub:
      group:
        id: hub-group

grpc:
  server:
    port: 9095
  client:
    hub-router:
      address: static://localhost:59090
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: PLAINTEXT

spring:
  kafka:
    consumer:
      enable-auto-commit: false
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  sql:
    init:
      mode: always
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5435/analyzer
    username: analyzer
    password: analyzer
